### ISSUE TITLE
Backend BibTex/BibLaTeX

### ISSUE THREAD

**Issue by daniel-richter** [hpi-swa-lab/hpitr#11]
Add `\usepackage[backend=bibtex]{biblatex}`, `\addbibresource{references.bib}`, and `\printbibliography` to sample document.

``` LaTeX
\documentclass[german,inproceedings]{hpitr}
\input{preamble}
\usepackage[backend=bibtex]{biblatex}
\addbibresource{references.bib}
\begin{document}
\input{content}
%\bibliography{references}
\printbibliography
\end{document}
```

**Comment by krono** [comment]
Sample document like this exists only for special purposes and is not distributed with this class.
Non-issue for now. (But it will bite me anyway)
