### ISSUE TITLE
Option clash for package blindtext in example-single.tex

### ISSUE THREAD

**Issue by sirexeclp** [hpi-swa-lab/hpitr#32]
`example-single.tex` loads the package like `\usepackage[math]{blindtext}`, but it will be loaded already by the hpitr document class,
since it is used in draft mode. All other examples don't use the draft mode.

**Comment by krono** [comment]
moep

**Comment by krono** [comment]
What is the error?
I cannot reproduce here

**Comment by sirexeclp** [comment]
Using the latest version i can also not reproduce it.
Maybe it was just a dirty build environment on my side.
